= Autres qualités (eXtreme Programming)
ifndef::backend-pdf[]
:imagesdir: images
endif::[]

Les facteurs de qualité présents dans ce document ne pourrait se passer de recommandations de l'eXtreme Programming.

== Une fois et une seule

Kent Beck  (eXtreme Programming <<xp>>) identifie les 2 principes suivants :

1. Le système (code et tests pris dans leur ensemble) doit *communiquer* tout ce que vous avez l'intention de communiquer (comprendre le code *est* la documentation, à rapprocher de link:index.html#documentation[#Documentation])

2. Le système ne doit contenir *aucune duplication de code*

NOTE: Ces deux caractéristiques constituent la règle : *Une Fois et Une Seule*.


== Convention de nommage
Puisque tous les développeurs interviennent sur tout le code, il est indispensable d'établir et de respecter des normes de nommage pour les variables, méthodes, objets, classes, fichiers, etc.

== Le code est toujours testé
Présence obligatoire de tests unitaires associés au code.
Lorsqu'un bogue survient, un test unitaire est créé.

[bibliography]
== References
- [[xp]]eXtreme Programming, Kent Beck, CampusPress
- [[xp2, 2]] L’eXtreme Programming, J.L. Bénard, L. Bossavit, R. Médina, D. Williams, Editions Eyrolles
- https://fr.wikipedia.org/wiki/Extreme_programming[eXtreme Programming - wikipedia]


