= Robustesse-Cyber-Securité
ifndef::backend-pdf[]
:imagesdir: images
endif::[]

Ce facteur de qualité est une application de la link:index.html#robustesse[robustesse],
dans le cadre de la cyber sécurité.

====
La qualité **robustesse - cyber sécurité** relève de la prise en compte de principes et de bonnes pratiques visant à résister à des usages malveillants du logiciel (cybersécurité).
====

Exemples de bonnes pratiques

====
• *principe de moindre privilège*. Stipule qu’un cas d'utilisation  ne doit bénéficier que des privilèges strictement nécessaires à l’exécution de son code.

L'objectif étant de _restreindre les conséquences possibles de comportements inattendus d’un composant,
qu’il s’agisse d’un bogue ou de son détournement par un attaquant_.  <<gansii>>
====

====
• *réduction de la surface d'attaque*. _La surface d'attaque ou surface d'exposition est la somme des différents points faibles (les « vecteurs d'attaque ») par lesquels un utilisateur non autorisé (un « pirate ») pourrait potentiellement s'introduire dans un environnement logiciel et en soutirer des données_.footnote:[https://fr.wikipedia.org/wiki/Surface_d%27attaque#R%C3%A9duction_de_la_surface_d'attaque[Surface d'attaque - wikipédia]]

Une approche pour améliorer la sécurité de l'information est de *réduire* la surface d'attaque d'un système, d'un logiciel. Les stratégies de base de réduction d'une surface d'attaque sont les suivants :

- Limitation du nombre de points d'entrée disponibles (par exemple, interdire tout accès à la base de données de l'application en dehors de celle-ci ou d'un compte admin en ssh)
- Limitation des dépendances tiers
- Réduction de la quantité de code en cours d'exécution

====

====
• *défense en profondeur*

_Terme emprunté à une technique militaire destinée à retarder l'ennemi. Consiste à exploiter plusieurs techniques
indépendantes de sécurité, afin de *réduire le risque* lorsqu'un composant particulier de sécurité est compromis ou défaillant_.

En pratique, pour certaines actions aux lourdes conséquences (suppression de données sans possibilité de revenir en arrière, ou à impact métier fort) le développeur pourra appliquer une mesure d'authentification préalable, même si l'utilisateur est considéré comme ayant les droits à ce moment là (dans le cas d'un défaut de sécurité côté utilisateur -- une autre personne se faisant passer pour lui suite à un vol de jeton d'authentification). Voir https://www.ssi.gouv.fr/agence/publication/le-modele-zero-trust/[ANSSI le modele _zero trust_]

NOTE: Attention cependant de ne pas tomber dans le travers de la programmation défensive. Voir : https://fr.wikipedia.org/wiki/D%C3%A9fense_en_profondeur[Défense en profondeur - wikipédia])
====

====

• *valeurs par défaut sécurisées*.

Ce peut être des valeurs initiales d'un formulaire construit dynamiquement ou  des valeurs
par défaut de connexions à une base de données, etc.

Exemple : https://www.zdnet.fr/actualites/mongodb-mal-configure-cela-pourrait-vous-couter-cher-39822708.htm[600TB de données MongoDB  exposées sur la toile]
====


[bibliography]
== References
- [[[gansii]]] https://www.ssi.gouv.fr/uploads/2017/12/guide_cloisonnement_systeme_anssi_pg_040_v1.pdf[guide ANSSI sur le cloissement système - 2017]
- https://social.technet.microsoft.com/wiki/contents/articles/7100.the-security-development-lifecycle.aspx[the security development lifecycle - Microsoft]
